server:
  port: 88

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
          - Path=/baidu
        filters:
          - StripPrefix=1

      - id: qq_route
        uri: http://www.qq.com
        predicates:
          - Path=/qq
        filters:
          - StripPrefix=1

      - id: product_route
        uri: lb://gulimall-product
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: member_route
        uri: lb://gulimall-member
        predicates:
          - Path=/api/member/**
        filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: ware_route
        uri: lb://gulimall-ware
        predicates:
          - Path=/api/ware/**
        filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}

      - id: third_party_route
        uri: lb://gulimall-third-party
        predicates:
          - Path=/api/third/**
        filters:
          - RewritePath=/api/third/(?<segment>.*), /$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
