server:
  port: 3000

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tJmiWk3yetRyacQZu2o
      secret-key: U6LrAYxw0Z3Hh2mkoXD8xgaB3pa1yI
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimallspace
